#!/bin/bash
if [ $# -eq 1 ]
then
	inputfile="-"
elif [ $# -eq 2 ]
then
	if [ -f "$1" ]
	then
		inputfile=$1
	else
		inputtext=$1
	fi
	shift;
else
	echo 'Usage: prewrite [text|filename] filename' 2>&1; exit 2
fi
if [ -z "$inputfile" ] 
then
	cat $1 | xclip -i && echo "$inputtext" > $1 && xclip -o >> $1
else
	cat $1 | xclip -i && cat "$inputfile" > $1 && xclip -o >> $1
fi

#case $# in
#1) inputtext="-" ;;
#2) if
#*) echo 'Usage: prewrite [text] filename' 2>&1; exit 2
#esac
#cat "$inputtext";
#cat $1 | xclip -i && echo "$inputtext" > $1 && xclip -o >> $1
